---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Wait for cloud-init to finish
      ansible.builtin.wait_for:
        path: /var/lib/cloud/instance/boot-finished
        state: present
    - name: Make sure python3 is installed
      package:
        name: python3
        state: present
    - name: get EPEL on AWS Linux
      command: amazon-linux-extras install epel -y
      when: (ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2')
